--
-- PostgreSQL database dump
--

\restrict 9498Xyf9aW2T1NxUMBbZyvs7Mh3KEXI92BMpTI53vQCblnaZw6I9lnae8TS1C7u

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-06-14 01:36:33 -05

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 16390)
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    id_usuario integer NOT NULL,
    apellido character varying(50) NOT NULL,
    clave character varying(255) NOT NULL,
    dni character varying(8) NOT NULL,
    email character varying(255) NOT NULL,
    nombre character varying(50) NOT NULL,
    tipo character varying(255) NOT NULL,
    CONSTRAINT usuario_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['POSTULANTE'::character varying, 'TUTOR'::character varying])::text[])))
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16404)
-- Name: usuario_id_usuario_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario ALTER COLUMN id_usuario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_usuario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4482 (class 0 OID 16390)
-- Dependencies: 219
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario (id_usuario, apellido, clave, dni, email, nombre, tipo) FROM stdin;
\.


--
-- TOC entry 4489 (class 0 OID 0)
-- Dependencies: 220
-- Name: usuario_id_usuario_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuario_id_usuario_seq', 471, true);


--
-- TOC entry 4330 (class 2606 OID 16407)
-- Name: usuario uk5171l57faosmj8myawaucatdw; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT uk5171l57faosmj8myawaucatdw UNIQUE (email);


--
-- TOC entry 4332 (class 2606 OID 16409)
-- Name: usuario ukma71x4n4tydibsd9qt0m71le7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT ukma71x4n4tydibsd9qt0m71le7 UNIQUE (dni);


--
-- TOC entry 4334 (class 2606 OID 16411)
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario);


-- Completed on 2026-06-14 01:36:33 -05

--
-- PostgreSQL database dump complete
--

\unrestrict 9498Xyf9aW2T1NxUMBbZyvs7Mh3KEXI92BMpTI53vQCblnaZw6I9lnae8TS1C7u

