spring.ai.google.genai.api-key=AQ.Ab8RN6Kb7gzTqMZ7YFEqUv3a9EwGc8yJVLkqMB8xUDt_ZMG6mQ
spring.ai.google.genai.chat.model=gemini-2.5-flash
spring.ai.google.genai.chat.options.temperature=0.8
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/consejero_vocacional
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true
